name: Reports
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '5 5 * * *'
  workflow_dispatch:

env:
  NEOVIM_DIR: ${{ format('{0}/neovim', github.workspace) }}
  NEOVIM_REPO: 'neovim/neovim'
  DOC_DIR: ${{ format('{0}/gh-pages', github.workspace) }}
  DOC_REPO: ${{ github.repository }}

jobs:
  reports:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          path: gh-pages
          ref: gh-pages
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          repository: ${{ env.NEOVIM_REPO }}
          path: 'neovim'

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Set $NEOVIM_COMMIT
        run: |
          cd "$NEOVIM_DIR"
          printf 'NEOVIM_COMMIT=%s\n' $(git rev-parse HEAD) >> $GITHUB_ENV

      - name: Setup git config
        run: |
          git config --global user.name 'marvim'
          git config --global user.email 'marvim@users.noreply.github.com'

      - name: Install apt packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake build-essential cmake doxygen gcc-multilib gettext gperf libtool-bin locales ninja-build pkg-config clang-tools

      - name: Update user documentation
        env:
          MAKE_CMD: ninja
        run: |
          ${GITHUB_WORKSPACE}/ci/user-docu.sh
          cd "$DOC_DIR"
          git add --all .
          git commit -m 'user docu: Automatic update'


      # - name: Push update
      #   run: |
      #     cd "$DOC_DIR"
      #     ${GITHUB_WORKSPACE}/ci/truncate-history.sh
      #     git push --force https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
